### ISSUE TITLE
Observar parâmetros para verificação de corretude do diário do dia 20/07/2022

### ISSUE THREAD

**Issue by danielfireman** [emanuelucas04/ifal-qd#18]
Preencher essa issue com os seguintes dados:

- Número de municípios no diário
- Nomes dos municípios no diário
- Códigos de identificação dos atos de cada município
- Cabeçalho

**Comment by danielfireman** [comment]
Olá @emanuelucas04 

Está faltando apenas os Códigos de identificação dos atos de cada município, certo?

**Comment by emanuelucas04** [comment]
Aqui estão os códigos identificadores:

- Arapiraca:
0C158AB2 
C190BB6E

- Atalaia:
05983BF1 

- Barra de São Miguel:
EED76B88 

- Branquinha: 
F6488DD6 
BD745E50 
B95A1332 
81A1F74D 

- Cacimbinhas: 
3C2660A9 
56213819 
614B761D 

- Campo Alegre: 
E835D665
0307EC31 
6D208836 

- Canapi: 
66831D18 
3CCA3168 
2BB86E99 
55DFBE10
9468F57C 

- Carneiros: 
42BC8D8F

- Coqueiro Seco: 
DC9F2381
D3C77E4E

- Delmiro Gouveia: 
6E40D25C 
6BECBF90 
00BBEA7E 
12F6DD12 
4274EAE3 
3D88B988 
DE7FE49D
F0673D62 
A1C78859 
F12D71B3 
C16ABF70 
87F7815B
F0CB7AF7
2984B2C3 
22E0450F 
604A97BB 
51C66CE8 
707CE7EE
9443882A

- Dois Riachos: 
D53F66CD 

- Feliz Deserto: 
1F37D5B4 
B1FFFA14 

- Inhapi: 
D9B70F32 
9782CC7D 
D504F853
996B6833 
E7029FAF 
2C968D86
76DE50D6 

- Joaquim Gomes: 
5E57D2DE 
B8935313
2593EE25
DD45F75A 
E1EDBC7E

- Lagoa da Canoa: 
B5F3B7DF 
95324BFC
BDA0B046
66FF496A 

- Maragogi: 
1D1E0969 
4335B866

- Maravilha: 
F6010E26
FFFAAD68 
6BE9A18A
468B7CB2

- Marechal Deodoro: 
165ED33D 
47FB549C
11A60F1D
D3179886 
A960E7CB 
C3106B8A 
A2849C30 
9F5FDF4A 

- Mata Grande: 
616B89C7 
1D037167 

- Messias: 
9948E854 
A38F69E1

- Minador do Negrão: 
6F615D47 
9F19062A 

- Olho D'água do Casado: 
501A5430
C92E7607 

- Olho D'água das Flores: 
B9388A88 
B67E3417
F22F69A5 
D1C28269

- Pão de Açúcar: 
8430FFEA 
65FA1E2A 

- Pariconha: 
F46C792B 

- Pilar: 
D2E28E15 
3CA116A4 
CE5BE525 

- Pindoba: 
CFB8F5D7 

- Piranhas: 
54B9D73C
6FC13F12 
63CA3E0B

- Porto Calvo: 
AE050FE2 
29B93233 
8CAE25B8
39833460
8C67696D 

- Porto Real do Colégio: 
FA673901

- Quebrangulo: 
E5606EE3
7A2D714E

- Rio Largo: 
EBE98472 
DEFAB4A0 
BAE56AC4
7F79D483 
9EFF1D84
A3654859

- Santa Luzia do Norte: 
1467EF09
F60107DB 
29546E78
90F41405
1A06469D 
BFF3D0D4
D9E2F2E7 
6175B83E
E37E4ED4

- Santana do Mundaú: 
81144410 
2C27441F 
074E8495

- São José da Tapera: 
853C66CF 
DD057881 
A35561F7
ABF47BBF

- São Miguel dos Milagres: 
2CC99CBD
1BC6A757
B64F6441 
A2E9C0E2 

- Tanque D'arca: 
8AB1ACBB
81077412 
A090DE30

- Taquarana: 
6DF27988
5378364B 
97B8F36A
E8878168 
022C9F12

- Teotônio Vilela: 
2CCBF9EE

- Viçosa: 
E4A302DF

**Comment by danielfireman** [comment]
Agora é trabalhar com @alex-custodio para criar o teste automático que verificará esses aspectos do diário. Começando pelo número e nomes dos municípios no diário.
