### ISSUE TITLE
Observar parâmetros para verificação de corretude do diário do dia 29/08/2022

### ISSUE THREAD

**Issue by danielfireman** [emanuelucas04/ifal-qd#19]
Preencher essa issue com os seguintes dados:

- Número de municípios no diário
- Nomes dos municípios no diário
- Códigos de identificação dos atos de cada município
- Cabeçalho

**Comment by alex-custodio** [comment]
Diário Municipal 29/08/2022

- `33` Municípios

- MUNICÍPIOS: 

`Anadia,
Arapiraca,
Atalaia,
Cacimbinhas, 
Cajueiro,
Campo Alegre, 
Canapi,
Coqueiro Seco, 
Craíbas,
Delmiro Gouveia,
Estrela de Alagoas,
Ibateguara,
Jequiá da Praia,
Junqueiro,
Maravilha,
Marechal Deodoro,
Maribondo,
Messias,
Novo Lino,
Olho D’água do Casado,
Ouro Branco,
Palestina,
Pariconha,
Pilar,
Piranhas,
Quebrangulo,
Rio Largo,
Mundaú,
São José da Laje,
São Luís do Quitunde,
Traipú,
Viçosa,
Maragogi
`

- CABEÇALHO: 

`Alagoas , 29 de Agosto de 2022 • Diário Oficial dos Municípios do Estado de Alagoas • ANO IX | Nº 1869`

**Comment by danielfireman** [comment]
Massa! Temos o suficiente para começar um teste automatizado.
