### ISSUE TITLE
Problemas do Final do Diário

### ISSUE THREAD

**Issue by alex-custodio** [emanuelucas04/ifal-qd#9]
Lembrar de que no final do diário contém **tabelas**:
Logo após as informações de leis aprovadas e sancionadas pela câmara municipal de Maragogi.

## Conteúdo das Tabelas
- Tabelas referentes às Leis de Diretrizes Orçamentárias, como metas fiscais por exemplo.
Ao que parece, esse conteúdo realmente faz parte do município de Maragogi.

**Comment by danielfireman** [comment]
Vai ser resolvido com #17
